### ISSUE TITLE
Consider alternatives for the activesupport dependency

### ISSUE THREAD

**Issue by piotrmurach** [tomtt/bulldoze_renamer#1]
Hi Tom 👋 

Happy to see a new CLI tool written in Ruby! This is a topic I enjoy the most and spend a lot of OSS time on.

I'm opening this issue more as a discussion point. This is my attempt at helping to make your `bulldoze_renamer` tool even better. Please free to disregard if you don't agree with the points I'm going to make. 

I noticed that you rely on the `activesupport` dependency for the purpose of inflecting cases. The `activesupport` is a rather 'heavy' dependency. It's a large codebase with about 250 files(I did I quick count as I was curious). The gem also has 5 runtime dependencies. That's a lot of code, wouldn't you agree? This will impact installation time and translate to how fast your CLI tool runs. 

I'm not sure what your future plan is for the library but considering that currently you only need to inflect cases, maybe you could consider alternative gems that do only that? For example, I wrote [strings-case](https://github.com/piotrmurach/strings-case) to convert between different cases. Please don't read it as me trying to sell you on my library. I use it as a demonstration as it happens to match your requirements. But please use whatever you find appropriate. The main point still holds true, there may be a more lightweight alternative in the Ruby ecosystem.

**Comment by tomtt** [comment]
My reason to resorting to active record (indeed incurring a large penalty in "dead" code to me in the library) is to be consistent with how AS currently does inflections and match that. I was worried that in order to get consistency I would have to copy all the AS code and tests into my project. I was also thinking by using AS that if people already have exceptions to inflections set up in their project, they could easily employ that in the renamer as well. Another reason was that I am not myself particularly familiar with that part of AR and this project was a quick fix to scratch my own itch and this was the quickest way. I also reckon most ruby developers have AR on their system anyway, but I agree as an all purpose tool it would be better if it does not have to include it.

If this project turns out to become popular I'm open to find a good way to have AS-compatible inflections without including all of AS. Thank you for your consideration and suggestion.

Would you claim [strings-case](https://github.com/piotrmurach/strings-case) to be compatible with AR cases?

**Comment by tomtt** [comment]
I think what I would like to do in future is have an ActiveSupport compatible mode which would `require` which would only work if the user has it installed on their system. Then by default I could have a more light-weight library like yours which is fine for most use cases.

Thanks for the suggestion...

**Comment by piotrmurach** [comment]
Thank you for explaining your reasoning. Using `activesupport` to get to the release as quickly as possible makes sense.


My goal wasn't a parity with `activesupport` per se. I took a different implementation approach which I hope improves on the situation.

One improvement is to do with Unicode characters support:

```ruby
ActiveSupport::Inflector.underscore("ЗдравствуйтеПривет")
# => "ЗдравствуйтеПривет"
```

which `strings-case` handles:

```ruby
Strings::Case.underscore("ЗдравствуйтеПривет") 
# => "здравствуйте_привет"
```

Another thing is handling irregular strings with whitespace:

```ruby
ActiveSupport::Inflector.underscore("supports IPv6 on iOS?")
# => "supports i_pv6 on i_os?"
```

```ruby
Strings::Case.underscore("supports IPv6 on iOS?")
# => "supports_ipv6_on_ios"
```

I think confirming compatibility with `activesupport` for the `dasherize`, `underscore` and `camelize` methods is a useful proposition. I will add this to my list to copy tests to see how compatible the two gems are. I think a note that confirms compatibility will help users decide. 

Again, thank you for your comments as they will surely help me refine the `strings-case` gem.

I definitely will keep my fingers crossed for your gem to succeed. We need more command-line tools in Ruby ecosystem!
